[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/cnm-sw.js"
  [headers.values]
  Cache-Control = "no-store"

  [[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

