[build]
  command = "" # no build step
  publish = "src"

[[headers]]
  for = "/cnm-sw.js"
  [headers.values]
  Cache-Control = "no-store"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"


